language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t lucasrohlf/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true lucasrohlf/docker-react npm run test -- --coverage